tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/bundle'
tap 'common-fate/granted'

brew 'ansible'
brew 'awscli'
brew 'gh'
brew 'git'
brew 'mackup'
brew 'node'
brew 'redis'
brew 'yarn'
brew 'granted'

cask 'session-manager-plugin'
cask 'docker'
cask 'firefox'
cask 'github'
cask 'iterm2'
cask 'phpstorm'
cask 'postman'
cask 'sequel-ace'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'

cask 'font-victor-mono'
